# Generated by Django 5.2.7 on 2025-12-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bin',
            unique_together={('bin_name', 'warehouse')},
        ),
    ]
